"""
Smart Health Simulation Framework for VITA-BAND AI
Generates realistic, deterministic synthetic physiological and environmental sensor data
for AI development, testing, validation, and dashboard demonstrations.

DISCLAIMER: All data generated by this engine is synthetic and simulated.
It does not represent real patient data or clinical recordings.
"""
import math
import random
import time
from datetime import datetime
from typing import Dict, Any, List, Optional

from backend.models.schemas import (
    SimulationType,
    SimulationScenario,
    SensorReading,
)


class SmartHealthSimulator:
    """
    Deterministic physiological & environmental simulation engine.
    Simulates:
      - ECG P-Q-R-S-T waveform buffer (100 Hz, 100 samples)
      - EMG muscle contraction & fatigue signal buffer (100 samples)
      - MAX30102 Heart Rate (BPM) & SpO2 (%)
      - MPU6050 3-axis Accelerometer & Gyroscope
      - DHT22 Body/Skin Temperature (°C) & Ambient Humidity (%)
    """

    def __init__(self):
        self.scenario: SimulationType = SimulationType.NORMAL
        self.active: bool = False
        self.duration_seconds: int = 60
        self.start_time: float = time.time()
        self.severity: float = 0.8
        self.noise_level: float = 0.05
        self.baseline_hr: float = 72.0
        self.baseline_temp: float = 36.8
        self.baseline_spo2: float = 98.5
        self.baseline_humidity: float = 50.0
        self.step_counter: int = 0
        self.fall_state: str = "none"  # "none", "falling", "impact", "post_fall"
        self.fall_timer: int = 0

    def start_scenario(
        self,
        scenario: SimulationType,
        duration: int = 60,
        severity: float = 0.8,
        noise_level: float = 0.05,
        duration_seconds: Optional[int] = None,
    ) -> SimulationScenario:
        """Activates a simulation scenario."""
        self.scenario = scenario
        self.active = True
        self.duration_seconds = duration_seconds if duration_seconds is not None else duration
        self.severity = max(0.1, min(1.0, severity))
        self.noise_level = max(0.0, min(0.5, noise_level))
        self.start_time = time.time()
        self.step_counter = 0
        self.fall_state = "none"
        self.fall_timer = 0
        return self.get_status()

    def stop_scenario(self) -> SimulationScenario:
        """Reverts to peaceful NORMAL baseline."""
        self.scenario = SimulationType.NORMAL
        self.active = False
        self.fall_state = "none"
        self.fall_timer = 0
        return self.get_status()

    def get_status(self) -> SimulationScenario:
        """Returns current scenario state."""
        elapsed = int(time.time() - self.start_time) if self.active else 0
        if self.active and elapsed >= self.duration_seconds:
            # Auto-revert back to NORMAL when duration expires
            self.scenario = SimulationType.NORMAL
            self.active = False

        return SimulationScenario(
            scenario_type=self.scenario,
            active=self.active,
            duration_seconds=self.duration_seconds,
            elapsed_seconds=elapsed,
            severity=self.severity,
            noise_level=self.noise_level,
            baseline_hr=self.baseline_hr,
            baseline_temp=self.baseline_temp,
            baseline_spo2=self.baseline_spo2,
        )

    def generate_reading(self) -> SensorReading:
        """Generates the next deterministic sensor reading packet."""
        self.step_counter += 1
        elapsed = time.time() - self.start_time if self.active else 0
        
        # Check expiry
        if self.active and elapsed >= self.duration_seconds:
            self.scenario = SimulationType.NORMAL
            self.active = False

        noise = random.uniform(-self.noise_level, self.noise_level)
        t = self.step_counter * 0.1

        # Defaults (NORMAL)
        hr = self.baseline_hr + math.sin(t * 0.3) * 3.0 + (noise * 10.0)
        spo2 = self.baseline_spo2 - (abs(noise) * 1.5)
        temp = self.baseline_temp + math.sin(t * 0.05) * 0.1 + (noise * 0.2)
        humidity = self.baseline_humidity + math.sin(t * 0.1) * 2.0
        accel_x = math.sin(t * 0.8) * 0.08 + (noise * 0.05)
        accel_y = math.cos(t * 0.8) * 0.08 + (noise * 0.05)
        accel_z = 0.98 + (noise * 0.04)
        gyro_x = noise * 2.0
        gyro_y = noise * 2.0
        gyro_z = noise * 2.0
        activity = "resting"
        fall_detected = False
        ecg_status = "normal"
        emg_status = "normal"
        emg_amplitude = 15.0  # uV resting

        # Scenario Modulations
        if self.scenario == SimulationType.HEAT_STRESS:
            # Progressive core & ambient temperature rise, compensatory tachycardia
            temp = 38.6 + (self.severity * 1.2) + (noise * 0.3)
            humidity = 72.0 + (self.severity * 15.0) + (noise * 3.0)
            hr = 122.0 + (self.severity * 25.0) + math.sin(t * 0.5) * 5.0
            spo2 = 96.0 - (self.severity * 2.0)
            activity = "unsteady"
            ecg_status = "tachycardia"
            emg_amplitude = 45.0

        elif self.scenario == SimulationType.DEHYDRATION:
            # Elevated HR, mild elevated temperature, low humidity
            temp = 37.9 + (self.severity * 0.6) + (noise * 0.2)
            humidity = 25.0 - (self.severity * 10.0)
            hr = 108.0 + (self.severity * 18.0) + (noise * 5.0)
            spo2 = 96.5
            activity = "resting"
            emg_amplitude = 30.0

        elif self.scenario == SimulationType.FATIGUE:
            # High EMG muscle strain, slightly lowered HR, sluggish movement
            hr = 88.0 + (noise * 4.0)
            temp = 37.1
            humidity = 55.0
            activity = "unsteady"
            emg_status = "high_fatigue"
            emg_amplitude = 220.0 * self.severity  # high amplitude muscle exhaustion

        elif self.scenario == SimulationType.ABNORMAL_VITALS:
            # Arrhythmia, extreme bradycardia/tachycardia oscillations
            phase = math.sin(t * 1.5)
            if phase > 0:
                hr = 148.0 + (noise * 12.0)
                ecg_status = "tachycardia"
            else:
                hr = 44.0 + (noise * 6.0)
                ecg_status = "bradycardia"
            spo2 = 91.0 - (self.severity * 4.0)
            activity = "resting"
            ecg_status = "arrhythmic"

        elif self.scenario == SimulationType.FALL:
            self.fall_timer += 1
            if self.fall_timer < 4:
                # Normal walk before fall
                activity = "walking"
                accel_x, accel_y, accel_z = 0.2, 0.4, 1.05
            elif self.fall_timer == 4 or self.fall_timer == 5:
                # Impact spike (> 3.5g)
                accel_x = 2.8 * self.severity
                accel_y = 1.9 * self.severity
                accel_z = 3.6 * self.severity
                gyro_x, gyro_y, gyro_z = 120.0, 180.0, 95.0
                activity = "fall_impact"
                fall_detected = True
            else:
                # Post-fall immobility on the floor
                accel_x, accel_y, accel_z = 0.05, 0.95, 0.1
                gyro_x, gyro_y, gyro_z = 0.0, 0.0, 0.0
                activity = "immobile"
                fall_detected = True
                hr = 115.0  # shock / stress response

        elif self.scenario == SimulationType.RESPIRATORY_RISK:
            # Sudden hypoxemia SpO2 < 88%, tachycardia compensation
            spo2 = 86.0 - (self.severity * 6.0) + (noise * 1.0)
            hr = 118.0 + (self.severity * 15.0)
            temp = 37.2
            activity = "unsteady"

        elif self.scenario == SimulationType.ENVIRONMENTAL_STRESS:
            # Extreme ambient environmental factors
            temp = 42.0 + (self.severity * 3.0)
            humidity = 88.0 + (self.severity * 8.0)
            hr = 95.0 + (noise * 5.0)
            activity = "resting"

        # Generate realistic 1-second ECG waveform (100 samples)
        ecg_samples = self._generate_ecg_buffer(hr, ecg_status)

        # Generate realistic 1-second EMG waveform (100 samples)
        emg_samples = self._generate_emg_buffer(emg_amplitude, emg_status)

        return SensorReading(
            timestamp=datetime.utcnow(),
            device_id="ESP32-VITABAND-01",
            heart_rate=round(max(35.0, min(220.0, hr)), 1),
            spo2=round(max(65.0, min(100.0, spo2)), 1),
            temperature=round(max(25.0, min(45.0, temp)), 2),
            humidity=round(max(10.0, min(100.0, humidity)), 1),
            accel_x=round(accel_x, 3),
            accel_y=round(accel_y, 3),
            accel_z=round(accel_z, 3),
            gyro_x=round(gyro_x, 2),
            gyro_y=round(gyro_y, 2),
            gyro_z=round(gyro_z, 2),
            activity=activity,
            fall_detected=fall_detected,
            ecg_signal=ecg_samples,
            emg_signal=emg_samples,
            ecg_status=ecg_status,
            emg_status=emg_status,
            battery_percentage=94,
        )

    def _generate_ecg_buffer(self, hr: float, status: str) -> List[float]:
        """
        Synthesizes a realistic 100-sample ECG strip matching instantaneous heart rate
        using Gaussian summation for P, Q, R, S, T waves.
        """
        samples = 100
        buffer = []
        # Cycle duration in seconds: 60 / hr
        cycle_sec = 60.0 / max(40.0, hr)
        freq = 1.0 / cycle_sec

        for i in range(samples):
            t = (self.step_counter * 0.1) + (i / 100.0)
            phase = (t * freq) % 1.0  # 0.0 to 1.0 in cardiac cycle

            # Gaussian wave model
            p_wave = 0.15 * math.exp(-((phase - 0.20) ** 2) / 0.001)
            q_wave = -0.15 * math.exp(-((phase - 0.35) ** 2) / 0.0004)
            r_wave = 1.20 * math.exp(-((phase - 0.40) ** 2) / 0.0006)
            s_wave = -0.25 * math.exp(-((phase - 0.45) ** 2) / 0.0005)
            t_wave = 0.30 * math.exp(-((phase - 0.65) ** 2) / 0.004)

            val = p_wave + q_wave + r_wave + s_wave + t_wave
            
            # Add arrhythmia or noise if flagged
            if status == "arrhythmic":
                val += 0.2 * math.sin(t * 12.0)
            
            # Baseline baseline wander and micro-noise
            val += 0.03 * math.sin(t * 0.5) + random.uniform(-0.015, 0.015)
            buffer.append(round(val, 3))

        return buffer

    def _generate_emg_buffer(self, amplitude: float, status: str) -> List[float]:
        """
        Synthesizes raw EMG interference pattern (motor unit action potential bursts).
        """
        samples = 100
        buffer = []
        for i in range(samples):
            # Stochastic high-frequency Gaussian firing
            firing = random.gauss(0, 1.0)
            # Burst modulation
            burst = 0.5 + 0.5 * math.sin((i / 20.0) * math.pi)
            emg_val = firing * amplitude * burst
            buffer.append(round(emg_val, 2))
        return buffer


# Global singleton simulator instance
simulator = SmartHealthSimulator()
